const products = [
  {
    _id: '1',
    name: 'Premium zalogaj box',
    image: '/images/IMG_0131.jpeg',
    description: 'Mini burgeri, mini pice, slani rolati i kanapei u elegantnom box pakovanju.',
    category: 'Slano',
    showcase: true,
    unit: 'kg',
    price: 2000.0,
    countInStock: 10,
    rating: 5.0,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Rodjendanko mix box',
    image: '/images/IMG_9565.jpeg',
    description: 'Slani rolati, carska pita, mini burgeri i zalogaji za proslave.',
    category: 'Slano',
    showcase: true,
    unit: 'kg',
    price: 1800.0,
    countInStock: 7,
    rating: 5.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Domaci zalogaj box',
    image: '/images/IMG_9533.jpeg',
    description: 'Kiflice, mini projice i pita sa sirom u domacem ketering stilu.',
    category: 'Slano',
    showcase: true,
    unit: 'kg',
    price: 1200.0,
    countInStock: 5,
    rating: 4.6,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Prazne kiflice box',
    image: '/images/prazneBox.jpg',
    description: 'Prazne kiflice, idealne za punjenje raznim namazima i nadevima po zelji.',
    category: 'Slano',
    unit: 'kg',
    price: 1000.0,
    countInStock: 18,
    rating: 4.9,
    numReviews: 15,
  },
  {
    _id: '5',
    name: 'Mini burgeri',
    image: '/images/miniBurger.png',
    description: 'Mali burgeri za rodjendane, proslave i poslovne pauze.',
    category: 'Slano',
    unit: 'kg',
    price: 2000.0,
    countInStock: 14,
    rating: 5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Mini hot dog',
    image: '/images/miniHotDog.png',
    description: 'Mini hot dog zalogaji sa mekanim pecivom i ukusnim nadevom.',
    category: 'Slano',
    unit: 'kg',
    price: 1500.0,
    countInStock: 16,
    rating: 4.7,
    numReviews: 9,
  },
  {
    _id: '7',
    name: 'Pita sa sirom',
    image: '/images/pitaSir.png',
    description: 'Domaca pita sa sirom, secena za uredno serviranje.',
    category: 'Slano',
    unit: 'kg',
    price: 900.0,
    countInStock: 9,
    rating: 4.8,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Kiflice sa sirom',
    image: '/images/kifliceSir.png',
    description: 'Fine slane kiflice sa sirom, pogodne za svaki sto.',
    category: 'Slano',
    unit: 'kg',
    price: 1000.0,
    countInStock: 11,
    rating: 5,
    numReviews: 17,
  },
  {
    _id: '9',
    name: 'Zeleni kanape',
    image: '/images/zeleniKanape.png',
    description: 'Kanape sa pestom, sirom i krastavcem, osvezavajuce i dekorativno.',
    category: 'Slano',
    unit: 'kg',
    price: 1250.0,
    countInStock: 11,
    rating: 5.3,
    numReviews: 13,
  },
   {
    _id: '10',
    name: 'Slani stapici',
    image: '/images/slaniStapici.png',
    description: 'Hrskavi slani stapici sa susamom, idealni za grickanje i serviranje uz umake.',
    category: 'Slano',
    unit: 'kg',
    price: 900.0,
    countInStock: 11,
    rating: 7.3,
    numReviews: 7,
  },
   {
    _id: '11',
    name: 'Happy kanape',
    image: '/images/kanapeHappy.png',
    description: 'Vesele kanapei sa kombinacijom sireva, povrca i delikatesnih dodataka, spremni za serviranje.',
    category: 'Slano',
    unit: 'kg',
    price: 1500.0,
    countInStock: 11,
    rating: 8,
    numReviews: 9,
  },
  {
    _id: '12',
    name: 'Mini pice',
    image: '/images/miniPica.png',
    description: 'Mekane mini pice sa raznovrsnim nadevima, idealne za rodjendane i proslave.',
    category: 'Slano',
    unit: 'kg',
    price: 1400.0,
    countInStock: 11,
    rating: 9,
    numReviews: 15,
  },
  {
    _id: '13',
    name: 'Oreo nugat krofnice box',
    image: '/images/IMG_0657.jpeg',
    description: 'Mini oreo i nugat krofnice za slatki sto.',
    category: 'Dezerti',
    showcase: true,
    unit: 'kom',
    price: 3000.0,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '14',
    name: 'Kokos jagoda krofnice box',
    image: '/images/IMG_0666.jpeg',
    description: 'Mini kokos i jagoda krofnice, nezne i dekorativne.',
    category: 'Dezerti',
    showcase: true,
    unit: 'kom',
    price: 1600.0,
    countInStock: 7,
    rating: 4.9,
    numReviews: 10,
  },
  {
    _id: '15',
    name: 'Kolaci mix box',
    image: '/images/IMG_0331.jpeg',
    description: 'Raznovrsni mini kolaci u porcijama za svedski sto.',
    category: 'Dezerti',
    showcase: true,
    unit: 'kg',
    price: 3500.0,
    countInStock: 8,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '16',
    name: 'Kolaci mix mini box',
    image: '/images/IMG_9842(1).jpg',
    description: 'Raznovrsni mini kolaci u porcijama za svedski sto u manjem pakovanju.',
    category: 'Dezerti',
    unit: 'kg',
    price: 2000.0,
    countInStock: 6,
    rating: 4.8,
    numReviews: 14,
  },
  {
    _id: '17',
    name: 'Bajadera',
    image: '/images/bajadera.jpg',
    description: 'Sitni kolaci sa cokoladom i orasastim notama.',
    category: 'Dezerti',
    unit: 'kg',
    price: 2800.0,
    countInStock: 10,
    rating: 4.9,
    numReviews: 16,
  },
  {
    _id: '18',
    name: 'Mafini',
    image: '/images/mafini.png',
    description: 'Mekani mafini u vise ukusa, dekorisani za slatki sto.',
    category: 'Dezerti',
    unit: 'kom',
    price: 150.0,
    countInStock: 12,
    rating: 4.9,
    numReviews: 11,
  },
  {
    _id: '19',
    name: 'Plazma sladoled',
    image: '/images/plazmaSladoled.png',
    description: 'Kremasti plazma sladoled za osvezavajuce slatko posluzenje.',
    category: 'Dezerti',
    unit: 'kom',
    price: 220.0,
    countInStock: 6,
    rating: 4.7,
    numReviews: 9,
  },
  {
    _id: '20',
    name: 'Kokos rolat',
    image: '/images/kokosRolat.png',
    description: 'Kremasti kokos rolat za ljubitelje egzoticnih ukusa.',
    category: 'Dezerti',
    unit: 'kg',
    price: 2000.0,
    countInStock: 15,
    rating: 6.7,
    numReviews: 4,
  },
   {
    _id: '21',
    name: 'Čokoladni kolač u čašici',
    image: '/images/cokoladniKolac.png',
    description: 'Kremasti čokoladni kolač u čašici, idealan za individualno posluženje.',
    category: 'Dezerti',
    unit: 'kom',
    price: 300.0,
    countInStock: 15,
    rating: 8.3,
    numReviews: 13,
  },
   {
    _id: '22',
    name: 'Ferero čašica',
    image: '/images/dezertiUCasi.png',
    description: 'Kremasti deserti u casicama sa ukusom Ferero Rocher bombona.',
    category: 'Dezerti',
    unit: 'kom',
    price: 310.0,
    countInStock: 10,
    rating: 6.7,
    numReviews: 16,
  },
  {
    _id: '23',
    name: 'Raspucanci',
    image: '/images/raspucanci.png',
    description: 'Kremasti raspucanci za hrskavo slatko posluzenje.',
    category: 'Dezerti',
    unit: 'kg',
    price: 1000.0,
    countInStock: 10,
    rating: 9.7,
    numReviews: 10,
  },
   {
    _id: '24',
    name: 'Čiz kejk u čašici',
    image: '/images/ciz.png',
    description: 'Kremasti čiz kejk u čašici, idealan za individualno posluženje.',
    category: 'Dezerti',
    unit: 'kom',
    price: 350.0,
    countInStock: 13,
    rating: 8.7,
    numReviews: 10,
  },
]

export default products
